### Veri Standardizasyonu

#### Standartlaştırma

In [1]:
import pandas as pd
import numpy as np
from sklearn import preprocessing

In [2]:
V1 = np.array([1,3,6,7,1,9])
V2 = np.array([7,5,8,12,2,3])
V3 = np.array([12,5,6,14,7,5])
df = pd.DataFrame(
        {
         "V1" : V1,
         "V2" : V2,
         "V3" : V3
        }        
)
df=df.astype(float)
df

V1    V2    V3
0  1.0   7.0  12.0
1  3.0   5.0   5.0
2  6.0   8.0   6.0
3  7.0  12.0  14.0
4  1.0   2.0   7.0
5  9.0   3.0   5.0

#### Normalizasyon

In [3]:
preprocessing.scale(df)

array([[-1.15079291,  0.24968808,  1.08543711],
       [-0.49319696, -0.34956332, -0.89666544],
       [ 0.49319696,  0.54931379, -0.61350793],
       [ 0.82199494,  1.74781659,  1.65175212],
       [-1.15079291, -1.24844042, -0.33035042],
       [ 1.47959089, -0.94881472, -0.89666544]])

#### Normalizasyon

In [4]:
preprocessing.normalize(df)

array([[0.07179582, 0.50257071, 0.86154979],
       [0.39056673, 0.65094455, 0.65094455],
       [0.51449576, 0.68599434, 0.51449576],
       [0.35491409, 0.60842415, 0.70982818],
       [0.13608276, 0.27216553, 0.95257934],
       [0.83925433, 0.27975144, 0.4662524 ]])

### Min-Max Dönüşümü

In [5]:
scaler=preprocessing.MinMaxScaler(feature_range=(10,20))

In [6]:
scaler.fit_transform(df)

array([[10.        , 15.        , 17.77777778],
       [12.5       , 13.        , 10.        ],
       [16.25      , 16.        , 11.11111111],
       [17.5       , 20.        , 20.        ],
       [10.        , 10.        , 12.22222222],
       [20.        , 11.        , 10.        ]])

#### Binarize Dönüşüm

In [7]:
binarizer=preprocessing.Binarizer(threshold=5).fit(df)

In [8]:
binarizer.transform(df)

array([[0., 1., 1.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 1.],
       [1., 0., 0.]])

#### 0-1 Dönüşümü

In [9]:
import seaborn as sns
tips=sns.load_dataset("tips")
df=tips.copy()
df_l=df.copy()
df_l.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [10]:
df_l["yeni_sex"]=df_l.sex.cat.codes
df_l

total_bill   tip     sex smoker   day    time  size  yeni_sex
0         16.99  1.01  Female     No   Sun  Dinner     2         1
1         10.34  1.66    Male     No   Sun  Dinner     3         0
2         21.01  3.50    Male     No   Sun  Dinner     3         0
3         23.68  3.31    Male     No   Sun  Dinner     2         0
4         24.59  3.61  Female     No   Sun  Dinner     4         1
..          ...   ...     ...    ...   ...     ...   ...       ...
239       29.03  5.92    Male     No   Sat  Dinner     3         0
240       27.18  2.00  Female    Yes   Sat  Dinner     2         1
241       22.67  2.00    Male    Yes   Sat  Dinner     2         0
242       17.82  1.75    Male     No   Sat  Dinner     2         0
243       18.78  3.00  Female     No  Thur  Dinner     2         1

[244 rows x 8 columns]

In [11]:
lbe=preprocessing.LabelEncoder()

In [12]:
df_l["daha_yeni_sex"]=lbe.fit_transform(df_l.sex)
df_l.head()

total_bill   tip     sex smoker  day    time  size  yeni_sex  daha_yeni_sex
0       16.99  1.01  Female     No  Sun  Dinner     2         1              0
1       10.34  1.66    Male     No  Sun  Dinner     3         0              1
2       21.01  3.50    Male     No  Sun  Dinner     3         0              1
3       23.68  3.31    Male     No  Sun  Dinner     2         0              1
4       24.59  3.61  Female     No  Sun  Dinner     4         1              0

#### "1 ve  Diğerleri(0) " Dönüşümü

In [13]:
df_l["yeni_gun"]=np.where(df.day.str.contains("Sat"),1,0)
df_l.head(20)

total_bill   tip     sex smoker  day    time  size  yeni_sex  \
0        16.99  1.01  Female     No  Sun  Dinner     2         1   
1        10.34  1.66    Male     No  Sun  Dinner     3         0   
2        21.01  3.50    Male     No  Sun  Dinner     3         0   
3        23.68  3.31    Male     No  Sun  Dinner     2         0   
4        24.59  3.61  Female     No  Sun  Dinner     4         1   
5        25.29  4.71    Male     No  Sun  Dinner     4         0   
6         8.77  2.00    Male     No  Sun  Dinner     2         0   
7        26.88  3.12    Male     No  Sun  Dinner     4         0   
8        15.04  1.96    Male     No  Sun  Dinner     2         0   
9        14.78  3.23    Male     No  Sun  Dinner     2         0   
10       10.27  1.71    Male     No  Sun  Dinner     2         0   
11       35.26  5.00  Female     No  Sun  Dinner     4         1   
12       15.42  1.57    Male     No  Sun  Dinner     2         0   
13       18.43  3.00    Male     No  Sun  Dinner     4         0   
14       14.83  3.02  Female     No  Sun  Dinner     2         1   
15       21.58  3.92    Male     No  Sun  Dinner     2         0   
16       10.33  1.67  Female     No  Sun  Dinner     3         1   
17       16.29  3.71    Male     No  Sun  Dinner     3         0   
18       16.97  3.50  Female     No  Sun  Dinner     3         1   
19       20.65  3.35    Male     No  Sat  Dinner     3         0   

    daha_yeni_sex  yeni_gun  
0               0         0  
1               1         0  
2               1         0  
3               1         0  
4               0         0  
5               1         0  
6               1         0  
7               1         0  
8               1         0  
9               1         0  
10              1         0  
11              0         0  
12              1         0  
13              1         0  
14              0         0  
15              1         0  
16              0         0  
17              1         0  
18              0         0  
19              1         1

### Çok sınıflı Dönüşüm

In [14]:
df_l["daha_yeni_gun"]=lbe.fit_transform(df_l.day)
df_l

total_bill   tip     sex smoker   day    time  size  yeni_sex  \
0         16.99  1.01  Female     No   Sun  Dinner     2         1   
1         10.34  1.66    Male     No   Sun  Dinner     3         0   
2         21.01  3.50    Male     No   Sun  Dinner     3         0   
3         23.68  3.31    Male     No   Sun  Dinner     2         0   
4         24.59  3.61  Female     No   Sun  Dinner     4         1   
..          ...   ...     ...    ...   ...     ...   ...       ...   
239       29.03  5.92    Male     No   Sat  Dinner     3         0   
240       27.18  2.00  Female    Yes   Sat  Dinner     2         1   
241       22.67  2.00    Male    Yes   Sat  Dinner     2         0   
242       17.82  1.75    Male     No   Sat  Dinner     2         0   
243       18.78  3.00  Female     No  Thur  Dinner     2         1   

     daha_yeni_sex  yeni_gun  daha_yeni_gun  
0                0         0              2  
1                1         0              2  
2                1         0              2  
3                1         0              2  
4                0         0              2  
..             ...       ...            ...  
239              1         1              1  
240              0         1              1  
241              1         1              1  
242              1         1              1  
243              0         0              3  

[244 rows x 11 columns]

### One-Hot Dönüşümü ve Dummy Değişken Tuzağı

In [15]:
df_one_hot=df.copy()

In [16]:
pd.get_dummies(df_one_hot,columns=["sex"], prefix=["sex"]).head()


total_bill   tip smoker  day    time  size  sex_Male  sex_Female
0       16.99  1.01     No  Sun  Dinner     2         0           1
1       10.34  1.66     No  Sun  Dinner     3         1           0
2       21.01  3.50     No  Sun  Dinner     3         1           0
3       23.68  3.31     No  Sun  Dinner     2         1           0
4       24.59  3.61     No  Sun  Dinner     4         0           1

In [17]:
pd.get_dummies(df_one_hot,columns=["day"], prefix=["day"]).head()


total_bill   tip     sex smoker    time  size  day_Thur  day_Fri  day_Sat  \
0       16.99  1.01  Female     No  Dinner     2         0        0        0   
1       10.34  1.66    Male     No  Dinner     3         0        0        0   
2       21.01  3.50    Male     No  Dinner     3         0        0        0   
3       23.68  3.31    Male     No  Dinner     2         0        0        0   
4       24.59  3.61  Female     No  Dinner     4         0        0        0   

   day_Sun  
0        1  
1        1  
2        1  
3        1  
4        1

### Sürekli Değişkeni Kategorik Değişkene Çevirme

In [18]:
dff=df.select_dtypes(['int64','float64'])

In [19]:
est=preprocessing.KBinsDiscretizer(n_bins=[3,2,2],encode="ordinal",strategy="quantile").fit(dff)

In [20]:
est.transform(dff)[:10]

array([[1., 0., 1.],
       [0., 0., 1.],
       [2., 1., 1.],
       [2., 1., 1.],
       [2., 1., 1.],
       [2., 1., 1.],
       [0., 0., 1.],
       [2., 1., 1.],
       [1., 0., 1.],
       [0., 1., 1.]])

### Değişkeni Index'e Index'i Değişkene Çevirmek

In [21]:
df["yeni_degisken"]=df.index
df

total_bill   tip     sex smoker   day    time  size  yeni_degisken
0         16.99  1.01  Female     No   Sun  Dinner     2              0
1         10.34  1.66    Male     No   Sun  Dinner     3              1
2         21.01  3.50    Male     No   Sun  Dinner     3              2
3         23.68  3.31    Male     No   Sun  Dinner     2              3
4         24.59  3.61  Female     No   Sun  Dinner     4              4
..          ...   ...     ...    ...   ...     ...   ...            ...
239       29.03  5.92    Male     No   Sat  Dinner     3            239
240       27.18  2.00  Female    Yes   Sat  Dinner     2            240
241       22.67  2.00    Male    Yes   Sat  Dinner     2            241
242       17.82  1.75    Male     No   Sat  Dinner     2            242
243       18.78  3.00  Female     No  Thur  Dinner     2            243

[244 rows x 8 columns]

In [22]:
df["yeni_degisken"]=df["yeni_degisken"]+10
