# Altküme Üzerinde İşlem Yapmak

In [1]:
import numpy as np

In [2]:
a=np.random.randint(10,size=(5,5))

In [3]:
a

array([[2, 2, 7, 8, 1],
       [4, 2, 7, 7, 7],
       [9, 8, 9, 0, 1],
       [2, 3, 3, 6, 7],
       [2, 8, 3, 5, 8]])

In [4]:
alt_a=a[0:3,0:2]

In [5]:
alt_a[0,0]=99999
alt_a[1,1]=888

In [6]:
alt_a

array([[99999,     2],
       [    4,   888],
       [    9,     8]])

In [7]:
a

array([[99999,     2,     7,     8,     1],
       [    4,   888,     7,     7,     7],
       [    9,     8,     9,     0,     1],
       [    2,     3,     3,     6,     7],
       [    2,     8,     3,     5,     8]])

In [12]:
m=np.random.randint(10,size=(5,5))

In [13]:
m

array([[6, 5, 0, 7, 4],
       [9, 9, 9, 9, 8],
       [1, 2, 4, 9, 8],
       [1, 3, 8, 5, 0],
       [1, 3, 9, 8, 3]])

In [14]:
alt_b=m[0:3,0:2].copy()

In [15]:
alt_b

array([[6, 5],
       [9, 9],
       [1, 2]])