# Array Sıralama(Sorting)

In [1]:
import numpy as np

In [2]:
v=np.array([2,12,4,5,7])

In [3]:
v

array([ 2, 12,  4,  5,  7])

In [4]:
np.sort(v)

array([ 2,  4,  5,  7, 12])

In [5]:
v.sort()

In [6]:
v

array([ 2,  4,  5,  7, 12])

In [8]:
m=np.random.normal(20,5,(3,3))

In [9]:
m

array([[17.14138913, 21.17798601, 16.23510559],
       [22.85292837, 18.21661035, 20.33558655],
       [27.21392711, 18.91585628, 20.32294884]])

In [10]:
np.sort(m,axis=1)

array([[16.23510559, 17.14138913, 21.17798601],
       [18.21661035, 20.33558655, 22.85292837],
       [18.91585628, 20.32294884, 27.21392711]])

In [11]:
np.sort(m,axis=0)

array([[17.14138913, 18.21661035, 16.23510559],
       [22.85292837, 18.91585628, 20.32294884],
       [27.21392711, 21.17798601, 20.33558655]])