# **Array Birleştirme (Concatenation)**

In [2]:
import numpy as np

In [4]:
x=np.array([1,2,3])

In [5]:
y=np.array([4,5,6])

In [8]:
np.concatenate([x,y])

array([1, 2, 3, 4, 4, 5, 6])

In [9]:
z=np.array([7,8,9])

In [10]:
np.concatenate([x,y,z])

array([1, 2, 3, 4, 4, 5, 6, 7, 8, 9])

 ## **İki boyutlu birleştirme**

In [12]:
a=np.array([[1,2,3],[4,5,6]])

In [14]:
np.concatenate([a,a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [15]:
np.concatenate([a,a],axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [16]:
np.concatenate([a,a],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])