# Fancy Index ile Elemanlara Erişmek

In [1]:
import numpy as np

In [2]:
v=np.arange(0,30,3)

In [3]:
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [4]:
v[1]

3

In [5]:
al_getir=[1,3,5]

In [6]:
al_getir

[1, 3, 5]

In [7]:
v[al_getir]

array([ 3,  9, 15])

# İki boyutta Fancy

In [8]:
m=np.arange(9).reshape((3,3))

In [9]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [10]:
satir=np.array([0,1])

In [11]:
sutun=np.array([1,2])

In [14]:
m[satir,sutun]

array([1, 5])

# Basit Index ile Fancy Index

In [19]:
m[2,[1,2]]

array([7, 8])

# Slice ile fancy

In [20]:
m[0:,[1,2]]

array([[1, 2],
       [4, 5],
       [7, 8]])