# Matematiksel İşlemler

In [1]:
import numpy as np

In [2]:
v=np.arange(6)

In [3]:
v

array([0, 1, 2, 3, 4, 5])

In [5]:
v-1

array([-1,  0,  1,  2,  3,  4])

In [7]:
#ufunc

In [8]:
np.subtract(v,1)

array([-1,  0,  1,  2,  3,  4])

In [9]:
np.add(v,1)

array([1, 2, 3, 4, 5, 6])

In [10]:
v**3

array([  0,   1,   8,  27,  64, 125], dtype=int32)

In [11]:
np.power(v,3)

array([  0,   1,   8,  27,  64, 125], dtype=int32)

In [12]:
v%2

array([0, 1, 0, 1, 0, 1], dtype=int32)

In [13]:
np.mod(v,2)

array([0, 1, 0, 1, 0, 1], dtype=int32)

In [14]:
np.absolute(np.array([-3]))

array([3])

In [15]:
np.sin(180)

-0.8011526357338304

In [16]:
v=np.array([1,2,3,4])

In [17]:
np.log(v)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [19]:
?np

Type:        module
String form: <module 'numpy' from 'D:\\anaconda\\lib\\site-packages\\numpy\\__init__.py'>
File:        d:\anaconda\lib\site-packages\numpy\__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://www.scipy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as `np`::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-

# cheatsheet

In [ ]:
# İstatistiksel İşlemler