# **Slicing ile Elemanlara Erişmek(Array Alt Kümesine Erişmek)**

In [2]:
import numpy as np

In [7]:
a=np.arange(20,30)

In [8]:
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [9]:
a[0:3]

array([20, 21, 22])

In [10]:
a[1::2]

array([21, 23, 25, 27, 29])

# İki Boyutlu Slice İşlemleri

In [13]:
m=np.random.randint(10,size=(5,5))
m

array([[1, 2, 8, 0, 4],
       [2, 3, 6, 9, 4],
       [9, 1, 2, 4, 2],
       [3, 6, 8, 3, 4],
       [1, 7, 0, 6, 1]])

In [14]:
m[:,0]

array([1, 2, 9, 3, 1])

In [15]:
m[:,0:3]

array([[1, 2, 8],
       [2, 3, 6],
       [9, 1, 2],
       [3, 6, 8],
       [1, 7, 0]])

In [16]:
m[:,2:4]

array([[8, 0],
       [6, 9],
       [2, 4],
       [8, 3],
       [0, 6]])

In [17]:
m[1:3,0:3]

array([[2, 3, 6],
       [9, 1, 2]])